#YAML
PATH: !!str "./Simulation_example"
experiment_data: !!str "simulation"
random_seed: 117

train_pre: False
train_main: False
validate: True

pretraining:
    func_optim: !!str "SGD" #from torch.optim
    n_features: !!int 150 #218
    alpha: !!int 0
    beta: !!int 13
    batch_size: !!int 30
    iter_critic: !!int 4
    dropout_prob: !!float 0.5

    data_prep:
        microarray: !!int 2
        simulation: !!int 0
        metabolomics: !!int 2

    gen_structure: [50, 100, 200]
    critic_structure: [200, 100, 50]

    max_epochs_1: !!int 500
    max_loss_1: !!float 3
    n_epochs_2: !!int 1000
    lr_1: [0.0005, 0.0001, 0.001]
    lr_2: [0.00001, 0.00005, 0.0001]
    rate_save: !!int 20
    diff_epochs: !!int 500
    max_loss_2: !!float 15
    min_loss_2: !!float -10
    alpha_instab: !!float 3

retraining: #[under, over]
    path_prePars: "./Simulation_example/Results/External_Results/Saved_Pars"
    func_optim: ["SGD", "SGD"] #from torch.optim
    n_features: [150, 150] #218
    alpha: [None, None]
    beta: [13, 13]
    batch_size: [10, 20]
    iter_critic: [2, 2]
    dropout_prob: [0.7, 0.7]

    data_prep:
        microarray: None
        simulation: None
        metabolomics: None

    gen_structure: [[50, 100, 200], [50, 100, 200]]
    critic_structure: [[200, 100, 50], [200, 100, 50]]

    max_epochs_1: [500, 500]
    max_loss_1: [3, 3]
    n_epochs_2: [5000, 5000]
    lr_1: [[0.0005, 0.0001], [0.0005, 0.0001]] #[0.0005, 0.0001, 0.001]
    lr_2: [[0.00001, 0.00005], [0.00001, 0.00005]]
    rate_save: [10, 10] #20, 20
    diff_epochs: [500, 500]
    max_loss_2: [15, 15]
    min_loss_2: [-15, -15]
    alpha_instab: [3, 3]
